import { expect, test } from "./fixtures";

test("three panels resize, persist, and preserve diagram tools", async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "System Architecture Designer" })).toBeVisible();
  const note = page.locator('article[data-target-id="game-concept"]');
  const originalStyle = await note.getAttribute("style");
  const separator = page.getByRole("separator", { name: "Resize left panel" });
  const box = (await separator.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + 150);
  await page.mouse.down();
  await page.mouse.move(box.x + 75, box.y + 150, { steps: 8 });
  await page.mouse.up();
  const resized = await separator.getAttribute("aria-valuenow");
  expect(Number(resized)).toBeGreaterThan(350);
  await page.getByRole("button", { name: "Collapse solution panel" }).click();
  await page.reload();
  await expect(separator).toHaveAttribute("aria-valuenow", resized!);
  await expect(page.getByRole("button", { name: "Expand solution panel" })).toBeVisible();
  await expect(note).toHaveAttribute("style", originalStyle!);
  await page.getByRole("button", { name: "Generate Diagram", exact: true }).click();
  await expect(page.getByRole("tab", { name: "Diagram", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("button", { name: "Download SVG" })).toBeEnabled();
  await page.getByRole("button", { name: "Edit source" }).click();
  await page.locator(".diagram-editor").fill("graph TD; A[Edited] --> B[Saved]");
  await page.getByRole("tab", { name: "Architecture", exact: true }).click();
  await page.getByRole("tab", { name: "Diagram", exact: true }).click();
  await expect(page.locator(".diagram-editor")).toHaveValue("graph TD; A[Edited] --> B[Saved]");
  await page.getByRole("button", { name: "Save diagram changes" }).click();
  await expect(page.locator(".overall-preview h2")).toContainText("v2");
  await page.getByRole("button", { name: "Full screen" }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.locator(".modal-close").click();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download SVG" }).click();
  expect((await downloaded).suggestedFilename()).toBe("architecture-diagram.svg");
  await page.getByRole("tab", { name: "Architecture", exact: true }).click();
  await page.getByRole("button", { name: "Edit architecture", exact: true }).click();
  await page.getByRole("textbox", { name: "Architecture source" }).fill("Manually revised architecture");
  await page.getByRole("button", { name: "Save architecture changes" }).click();
  await expect(page.locator(".overall-architecture")).toHaveText("Manually revised architecture");
  await expect(page.locator(".overall-preview h2")).toContainText("v3");
  await page.getByRole("button", { name: "Collapse project panel" }).click();
  await expect(page.getByRole("button", { name: "Expand project panel" })).toBeVisible();
  await page.setViewportSize({ width: 640, height: 900 });
  await page.getByRole("button", { name: "Expand project panel" }).click();
  await page.getByRole("button", { name: "Expand solution panel" }).click();
  await expect(page.getByRole("button", { name: "Expand project panel" })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
