import { expect, test } from "./fixtures";

test("project tabs isolate drafts, favorites, AI results and failed saves", async ({ page, request }) => {
  test.setTimeout(60000);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.setViewportSize({ width: 1600, height: 1100 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "System Architecture Designer" })).toBeVisible();
  const a = await page.evaluate(() => localStorage.getItem("ai-architecture-designer-project"));
  const prompt = page.locator(".controls-section textarea");
  await prompt.fill("Project A requirements");
  await page.locator('article[data-target-id="target-audience"]').getByTitle("Favorite", { exact: true }).click();
  let release!: () => void;
  let started = false;
  const held = new Promise<void>((resolve) => { release = resolve; });
  await page.route("**/api/architecture/stream", async (route) => {
    if (route.request().postDataJSON().prompt === "Project A requirements") {
      started = true;
      await held;
      await route.fulfill({ contentType: "text/plain", body: "Architecture only for A" });
    } else await route.continue();
  });
  await page.getByRole("button", { name: "Generate Architecture", exact: true }).click();
  await expect.poll(() => started).toBe(true);
  // The tabs and new-project controls remain usable while A is generating.
  await page.getByRole("textbox", { name: "New project name" }).fill("Project B");
  await page.getByRole("button", { name: "New project", exact: true }).click();
  await expect(page.getByTestId("project-identity")).toContainText("Project B");
  const b = await page.evaluate(() => localStorage.getItem("ai-architecture-designer-project"));
  expect(a).not.toBe(b);
  await expect(prompt).toHaveValue("");
  await expect(page.locator("article.note")).toHaveCount(0);
  await expect(page.getByRole("button", { name: /Favorites/ })).toContainText("0");
  await prompt.fill("Project B requirements");
  await page.getByRole("button", { name: /Add Sticky Note/ }).click();
  await page.locator("article.note textarea").fill("B note");
  await page.getByRole("button", { name: "Generate Architecture", exact: true }).click();
  await expect(page.locator(".overall-preview h2")).toContainText("v1");
  release();
  await expect.poll(async () => (await (await request.get(`/api/projects/${a}/workspace`)).json()).overall?.architecture).toBe("Architecture only for A");
  await expect(prompt).toHaveValue("Project B requirements");
  await expect(page.locator(".overall-preview")).not.toContainText("Architecture only for A");
  await page.getByRole("tab", { name: /Existing project/ }).click();
  await expect(prompt).toHaveValue("Project A requirements");
  await expect(page.getByRole("button", { name: /Favorites/ })).toContainText("1");
  await expect(page.locator(".overall-preview")).toContainText("Architecture only for A");
  await page.getByRole("button", { name: "Edit architecture", exact: true }).click();
  await page.getByRole("textbox", { name: "Architecture source" }).fill("A uncommitted result edit");
  await page.getByRole("tab", { name: /Project B/ }).click();
  await expect(page.getByRole("textbox", { name: "Architecture source" })).toHaveCount(0);
  await page.getByRole("tab", { name: /Existing project/ }).click();
  await expect(page.getByRole("textbox", { name: "Architecture source" })).toHaveValue("A uncommitted result edit");
  await page.getByRole("button", { name: "Cancel editing", exact: true }).click();
  await page.route(`**/api/projects/${a}/sync`, (route) => route.fulfill({ status: 503, json: { error: { message: "Simulated A save failure" } } }));
  await prompt.fill("A unsaved draft");
  // Switch immediately, before the debounce fires.
  await page.getByRole("tab", { name: /Project B/ }).click();
  await expect(prompt).toHaveValue("Project B requirements");
  await expect(page.getByRole("tab", { name: /Existing project/ })).toContainText("error");
  await expect(page.locator(".database-status")).toContainText("Saved to SQLite");
  await page.getByRole("tab", { name: /Existing project/ }).click();
  await expect(prompt).toHaveValue("A unsaved draft");
  await expect(page.locator(".database-status")).toContainText("Simulated A save failure");
  await page.getByRole("button", { name: "Close Existing project", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("unsaved changes");
  await expect(prompt).toHaveValue("A unsaved draft");
  await page.unroute(`**/api/projects/${a}/sync`);
  await page.getByRole("button", { name: "Retry database" }).click();
  await expect(page.locator(".database-status")).toContainText("Saved to SQLite");
  const bState = await (await request.get(`/api/projects/${b}/workspace`)).json();
  expect(bState.snapshot.project.prompt).toBe("Project B requirements");
  expect(bState.snapshot.notes[0].content).toBe("B note");
  expect(bState.snapshot.favorites).toHaveLength(0);
  await page.getByRole("button", { name: "Close Existing project", exact: true }).click();
  await expect(page.getByRole("tab", { name: /Existing project/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Project list", exact: true }).click();
  await page.getByRole("region", { name: "Saved projects" }).getByRole("button", { name: `Existing project · ${a!.slice(0, 8)}`, exact: true }).click();
  await expect(prompt).toHaveValue("A unsaved draft");
  await expect(page.getByRole("button", { name: /Favorites/ })).toContainText("1");
  expect(errors).toEqual([]);
});
